dist:
  module: github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol
  name: otelcol-custom
  description: Custom OpenTelemetry Collector Contrib
  output_path: ./building-custom-collector/dist
  version: 0.138.0

receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/otlpreceiver

processors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor

exporters:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/otlphttpexporter
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/debugexporter
connectors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/routingconnector

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/zpagesextension

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider
